on-deman batch job demo
hashicorp/nomad-autoscaler-demos pull request #22
Opened 2021-04-10 02:12 UTC by lgfa29

This PRs introduces a new cluster scaling demo for on-demand batch jobs. It also adds the next version of the cloud infrastructure process. Currently only AWS is implement, but GCP and Azure will be added in future PRs.

It also handles issues such as #5, #7 and #8.

2021-04-12 10:32 UTC, jrasell requested changes
The servers module doesn’t use the availability zones variable to constrain the instance placement. I believe this was causing problems for me when testing the stack where the LB did not reach a point where the instance health check was passing. Updating the module to reference the AZ param fixed this.

I have not run through the whole demo yet but looking really good. Will there be an update or followup PR to add README details?

2021-04-12 16:19 UTC, lgfa29 commented on cloud/infrastructure/aws/terraform/modules/aws-nomad-network/variables.tf
> +
I didn't know Terraform would support complex variable structs like this. Thanks!

2021-04-13 20:28 UTC, cgbaker approved these changes
👍

2021-04-14 10:33 UTC, jrasell approved these changes

2021-04-14 14:17 UTC, merged